# None of these values should be shared. They should be kept with the tree
# creator.

# Used for generating secrets for each entity.
master_secret = "master_secret"

# Used for generating blinding factors for Pedersen commitments.
salt_b = "salt_b"

# Used as an input to the hash function when merging nodes.
salt_s = "salt_s"
