# Build platform and run tests

# Took inspiration from the following:
# 

name: CI

on:
  merge_group:
  pull_request:
    branches: [main]
    paths:
      - "**"
      - "!/*.md"
      - "!/**.md"

jobs:
  build:

    name: Build on (${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    env:
      RUST_BACKTRACE: full
      RELEASE: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo test --examples --tests --no-run
        # TODO rather use the below as apposed to the above, when benches are done
        # run: cargo test --all-targets --no-run

      - name: Test
        run: cargo test
